### ISSUE TITLE
Remove Codex files 

### ISSUE THREAD

**Issue by bueltge** [inpsyde/php-coding-standards#1]
If we should, do it use this repo, please remove the current files (https://github.com/inpsyde/Codex/tree/master/tools/CodeSniffer) on the codex repository so that we not have an redundant standards. Maybe we should leave a hint in the codex repo for that new ruleset.

**Comment by bueltge** [comment]
If we release the new version https://github.com/inpsyde/php-coding-standards/tree/psr, remove theme on the Codex repo and leave a hint to use this repo here.

**Comment by gmazzap** [comment]
That repo is deleted.

**Comment by bueltge** [comment]
I remove all files and change the readme to leave the hint to switch to this repo here - https://github.com/inpsyde/Codex/tree/master/tools/CodeSniffer
Thanks @gmazzap !
