### ISSUE TITLE
Error in detecting return type

### ISSUE THREAD

**Issue by websupporter** [inpsyde/php-coding-standards#12]
public function test() : bool
    {
        $var = 1;
        return null !== $var;
    }

Return type with no return (Inpsyde.CodeQuality.ReturnTypeDeclaration.MissingReturn)

**Comment by gmazzap** [comment]
This should be fixed in [v0.12.0](https://github.com/inpsyde/php-coding-standards/releases/tag/0.12.0)

Thanks to @widoz
