### ISSUE TITLE
Change php_codesniffer dependency to fix break in 3.3.0

### ISSUE THREAD

**Issue by Dinamiko** [inpsyde/php-coding-standards#16]
New version 3.3.0 introduced an issue regarding NoReturnType sniff.

As a quick fix we can change to `~3.2.3` and then increase the version again when it's fixed.

Related Issue in PHP_CodeSniffer repo:
https://github.com/squizlabs/PHP_CodeSniffer/issues/2049

**Comment by widoz** [comment]
From the changelog 

> T_RETURN_TYPE Token
>
> The T_RETURN_TYPE token has been deprecated and will be removed in version 4.
>
> The token was used to ensure array/self/parent/callable return types were tokenized consistently. But for namespaced return types, only the last part of the string (the class name) was tokenized as T_RETURN_TYPE. This was not consistent and so return types are now left using their original token types so they are not skipped by sniffs. The exception are array return types, which are tokenized as T_STRING instead of T_ARRAY, as they are used for type hints.
>
> Sniffs referencing this token type will continue to run without error until version 4, but will not find any T_RETUTN_TYPE tokens.

> To get the return type of a function, use the File::getMethodProperties() method, which now contains a return_type array index. This index contains the return type of the function or closer, or a blank string if not specified. If the return type is nullable, the return type will contain the leading? and a nullable_return_type array index in the return value will also be set to true. If the return type contains namespace information, it will be cleaned of whitespace and comments. To access the original return value string, use the main tokens array.

I guess in this case we have not to switch to a previous version but update our sniffers.

**Comment by Chrico** [comment]
Changed the version in current master. Will be included in next release 0.13.2

**Comment by gmazzap** [comment]
@Chrico this is not really "the" solution.

First of all the version requirement should not be fixed, `3.2.*` is ok.
But most importantly, if PHPCS have deprecated the argument we need to update our code to reflect that and use the new way to things.

So changing the version might be a temporary solution, but not the final one.

So this is issue need to stay open waiting for a better fix.

**Comment by Chrico** [comment]
That's why i just created - for now - a bugfix release, so we can continue to work without loading it by hand. It seems that Codesniffer has a breaking change in it, which we should handle to be compliant with future releases.
