### ISSUE TITLE
Move wimg/ to phpcompatibility/

### ISSUE THREAD

**Issue by thefrosty** [inpsyde/php-coding-standards#22]
Suggest updating the composer require for `wimg/php-compatibility`.

> Package wimg/php-compatibility is abandoned, you should avoid using it. Use phpcompatibility/php-compatibility instead.

**Comment by gmazzap** [comment]
Done in e9b466f, thanks

**Comment by thefrosty** [comment]
@gmazzap are you going to cut a release for this?

**Comment by gmazzap** [comment]
@thefrosty here's it https://github.com/inpsyde/php-coding-standards/releases/tag/0.13.4
