### ISSUE TITLE
PHPCS colors being wrongly displayed on windows

### ISSUE THREAD

**Issue by BlackHayate** [inpsyde/php-coding-standards#25]
In the file ruleset.xml on line 17 you append the parameter "colors" to every process of phpcs using your coding standards. While it probably looks great on Unix systems, the windows console cannot really display or process these symbols generated by it, leading to a confusing display.

Now my question would be if it wouldn't be better to remove this parameter, maybe missing some frontend cherries but overall achieving a greater compatibility?

In the end this feature is just a nice-to-have and not a necessity so in my opinion any dev that wants to use this feature can just append the parameter themselves while the main repo remains good to use for more systems.

**Comment by gmazzap** [comment]
Thanks, @BlackHayate your suggestion makes sense.

Honestly, I use Windows, but with git-bash and it looks very fine. I'll talk with other maintainers and we'll see if we can remove it.

**Comment by gmazzap** [comment]
Colors argument has been removed in 52edc0b
