### ISSUE TITLE
Tests should be filterable to run them separately

### ISSUE THREAD

**Issue by dnaber-de** [inpsyde/php-coding-standards#36]
Right now I can only run all tests at once which makes it hard to debug/investigate a single sniff or part of code. It would be nice to have a possibility to run a singe test fixture. This can be achieved using PHPUnit's data provider. So

    $ vendor/bin/phpunit --filter function-length-no-blank-lines

will run only the `function-length-no-blank-lines.php` fixture.

**Comment by gmazzap** [comment]
Merged with 6b2998b
