### ISSUE TITLE
Line length of use statements should not be checked

### ISSUE THREAD

**Issue by tzimpel** [inpsyde/php-coding-standards#39]
`Inpsyde.CodeQuality.LineLength.TooLong` should not check  for `use` statements.

When working with nested namespaces to organize code, length of namespaces can exceed 100 characters. This should not lead to validation errors against our coding standards.

**Comment by gmazzap** [comment]
Fixed in 6d0bda8

**Comment by gmazzap** [comment]
Included in [1.0.0-beta.7](https://github.com/inpsyde/php-coding-standards/releases/tag/1.0.0-beta.7).

Closing. Thanks for reporting.
