### ISSUE TITLE
Installation via composer fails

### ISSUE THREAD

**Issue by SergeyBeloglazov** [inpsyde/php-coding-standards#44]
I tried to install the package via composer, but it failed with some errors:

```
>composer require inpsyde/php-coding-standards --dev
Using version ^0.13.4 for inpsyde/php-coding-standards
./composer.json has been created
Running composer update inpsyde/php-coding-standards
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - dealerdirect/phpcodesniffer-composer-installer[v0.4.0, ..., v0.4.4] require composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
    - inpsyde/php-coding-standards 0.13.4 requires dealerdirect/phpcodesniffer-composer-installer ^0.4 -> satisfiable by dealerdirect/phpcodesniffer-composer-installer[v0.4.0, ..., v0.4.4].
    - Root composer.json requires inpsyde/php-coding-standards ^0.13.4 -> satisfiable by inpsyde/php-coding-standards[0.13.4].

You are using Composer 2, which some of your plugins seem to be incompatible with. Make sure you update your plugins or report a plugin-issue to ask them to support Composer 2.

Installation failed, deleting ./composer.json.

```

I'm using Windows 10, PHP 7.3.24, Composer 2.0.8

I cloned the package from github repository.  
"**composer install**" have worked fine.
It works normally in this way of installation.

**Comment by bueltge** [comment]
Hi @SergeyBeloglazov 
please try to enhance your `composer.json` with the values

```json
	"minimum-stability": "dev",
	"prefer-stable": true,
```
Public example will you find here https://github.com/bueltge/marksimple/blob/master/composer.json#L35

**Comment by SergeyBeloglazov** [comment]
Thank You! But it doesn't help.
It installs fine if I add it to require-dev section of composer.json:
```
{
	"require-dev": {
        "inpsyde/php-coding-standards": "*"
	}
}
```

`>composer install` installs the package well.


But it doesn't install with `>composer require ...` command when no composer.json in a directory, or it's empty, or it consists only of these settings:
```
{
    "minimum-stability": "dev",
    "prefer-stable": true
}

```
May be I had something missed in my Windows installation of the composer.
But if I try command
`composer require phpunit/phpunit --dev `

in an empty dir, it installs PHPUnit and other required packages and create a new composer.json

```
{
    "require-dev": {
        "phpunit/phpunit": "^9.5"
    }
}
```

**Comment by thefrosty** [comment]
I would suggest trying to target the `1.0.0-RC1` tag, as `*` still pulls `0.3.4`, which is not compatible with composer 2.

**Comment by SergeyBeloglazov** [comment]
Thank you!
It works with
`>composer require inpsyde/php-coding-standards:1.0.0-RC1 --dev `

If I use *, it installs 0.2:
```
    "packages-dev": [
        {
            "name": "inpsyde/php-coding-standards",
            "version": "0.2.0",
            
```

**Comment by bueltge** [comment]
I use the value `^1` and it works with Composer v2 and installs the Coding Standard with 1.0.0-RC.1. YOu can read the install tasks via actions on github - https://github.com/bueltge/marksimple/runs/1688680978?check_suite_focus=true

```json
    "require-dev": {
        "phpunit/phpunit": "^8.0",
        "inpsyde/php-coding-standards": "^1",
...
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "config": {
        "optimize-autoloader": true
    },
```

See an example of full [composer.json](https://github.com/bueltge/marksimple/blob/master/composer.json). 

Please close the issue if not longer necessary. Thx.

**Comment by SergeyBeloglazov** [comment]
OK, thank you! I will try your variant.

**Comment by gmazzap** [comment]
Closing this as it seems a solution was provided.
