### ISSUE TITLE
[Feature Request]: Add check for Emacs UTF-8 file header

### ISSUE THREAD

**Issue by tyrann0us** [inpsyde/php-coding-standards#50]
**Is your feature request related to a problem? Please describe.**
At Inpsyde, PHP files used to have the following file header:
```
<?php # -*- coding: utf-8 -*-
```
or 
```
<?php declare(strict_types=1); // -*- coding: utf-8 -*-
```
As of 2021-06-25, there are more than [15.000 PHP files](https://github.com/search?l=PHP&q=org%3Ainpsyde+coding%3A+utf-8&type=Code) with this header. It originates from Emacs and including it was adapted by developers undiscussed for years.

However, (nowadays) it doesn't make any sense to keep it. In fact, it is no longer used in most new packages and should be removed gradually from legacy packages too.

**Describe the solution you'd like**
* Add a coding standard check for the header that warns the user if the header is present.
* Make sure that `phpcbf` deletes it.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by gmazzap** [comment]
Fixed in #77
