### ISSUE TITLE
[Question] When using phpcbf there is a bug for the rule that leaves the first line with opening php tag

### ISSUE THREAD

**Issue by luislard** [inpsyde/php-coding-standards#52]
**Describe the bug**
Not sure if this bug should be tackled in here

Some auto fixing is not working as expected
Notice the **phpdeclare** at the right after running **phpcbf**
![image](https://user-images.githubusercontent.com/17932063/140127257-973b0865-3322-45a1-bf8e-d8437b0c3386.png)

**To Reproduce**
Have the following file with code:
```
<?php declare(strict_types=1); // -*- coding: utf-8 -*-
/*
 * This file is part of @package CCV\ElasticWPCustomizations
 *
 * (c) Inpsyde GmbH
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace CCV\ElasticWPCustomizations\Tests\Unit\Index\Mapping\Settings;
```

**Expected behavior**
![image](https://user-images.githubusercontent.com/17932063/140128243-924e0003-4e3f-4850-9c65-032ec1d6b4d9.png)

**System (please complete the following information):**
- OS: Ubuntu
- PHP Version 7.4-fpm under docker container

**Comment by gmazzap** [comment]
We should first find out which is the rule that does it...

**Comment by antonioeatgoat** [comment]
@luislard I've just tried it with PHP 8.0.22 and version of the package `^2@dev`, it looks to work correctly in my case.

Can you please check if you can still reproduce it with last version of the pacakge?

**Comment by gmazzap** [comment]
Looks finefor me as well. Closing.
