### ISSUE TITLE
[Feature Request]: Bump squizlabs/php_codesniffer

### ISSUE THREAD

**Issue by thefrosty** [inpsyde/php-coding-standards#57]
### Is your feature request related to a problem?

Can't update/install over PHPCS standards that require latest php_codesniffer version.

### Describe the desired solution

Currently `squizlabs/php_codesniffer` is locked at ~3.6.0, but now suggests `3.*` or latest is now 3.7.1.

### Describe the alternatives that you have considered

??

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gmazzap** [comment]
Hi @thefrosty, thank you.

This is done in master with #[6d7f5ab](https://github.com/inpsyde/php-coding-standards/commit/6d7f5ab7ff38c204a083e78c5a3bb7ceff55a21e) and will be added to next release.
