### ISSUE TITLE
[Feature Request]: Add a rule against unused imports

### ISSUE THREAD

**Issue by strangerkir** [inpsyde/php-coding-standards#58]
### Is your feature request related to a problem?

After code refactoring or merging, we often have redundant namespace imports with the `use` keyword. This is a dead code that does nothing but pollution. It's easy to overlook these lines.

### Describe the desired solution

Add a sniff raising warning or error on redundant namespace imports.

### Describe the alternatives that you have considered

Require the [code standard](https://github.com/slevomat/coding-standard) with this rule and just use it.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gmazzap** [comment]
We have added Slevomat standard as a dependency.

Thar standard has a lot of Sniffs, so we could use much more sniff besides the "unused use" proposed here.
But we need to gather consensus on the sniffs to require.

**Comment by gmazzap** [comment]
Closing in favor of #71
