### ISSUE TITLE
NoAccessors.NoGetter - don't check for native/psr interfaces

### ISSUE THREAD

**Issue by Chrico** [inpsyde/php-coding-standards#7]
Sometimes it is required to implement get/set or whatevery methods which are maybe not allowed by coding standard but fixed by an interface. 

Following error occurs in version 0.7.x - release:

```
Getters are discouraged. "Tell Don't Ask" principle should be applied if possible, and if getters are really needed consider naming methods after properties, e.g. name() instead of getName().(InpsydeCodingStandard.CodeQuality.NoAccessors.NoGetter)
```

As code example we've following:

```php
<?php declare(strict_types=1); # -*- coding: utf-8 -*-

class Foo implements IteratorAggregate
{


    public function getIterator(): Traversable
    {
        // snip
    }
}
```

Link: http://php.net/manual/en/iteratoraggregate.getiterator.php

----

Secondly it could be also possible to e.G. implement PSR-standard interfaces like [PSR container](https://github.com/php-fig/container) which are having a `get($id)` method.

**Comment by gmazzap** [comment]
The `getIterator` bug is already fixed in master, with https://github.com/inpsyde/php-coding-standards/commit/412336470cc51e645c6e9103da4bba611db2c9e9

The `get()` method is allowed because the regex that check for getters is `~(get|set)[_A-Z0-9]+~` which will not match for `get` (or `set`).

**Comment by gmazzap** [comment]
Releasee v0.8.0 which includes this fix.

**Comment by Chrico** [comment]
Nice! What i see so far is that following are missing:

- [Generator::getReturn](http://php.net/manual/en/generator.getreturn.php)

**Comment by gmazzap** [comment]
@Chrico there's not need for `getReturn`. There's no way you can _declare_ that method,because `Generator` is final, so can't be extended.

You can only _use_ that method. And _using_ a method does not trigger any problem with the style.

**Comment by Chrico** [comment]
arg, seems that i've missed that when browsing on phone...so i guess all `get`-methods are implement - for now. :)
