### ISSUE TITLE
[Feature Request]: Evaluate which "Slevomat" coding standard sniffs to use

### ISSUE THREAD

**Issue by gmazzap** [inpsyde/php-coding-standards#71]
### Is your feature request related to a problem?

In #58 @strangerkir Proposed to make use of the "unused use" sniff from [Slevomat coding standard](https://github.com/slevomat/coding-standard).

As part of #70, that standard will be effectively part of the dependencies of this package.

Consider the large amount of sniff it has, we could consider to use more of them, because I can see many of them have potential to be a good addition.

But we need to gather consensus on which to use. This issue is the place where we will track that progress, even though not sure yet which will be the vest way to do such thing.

### Describe the desired solution

Collect consensus on the standard to use, possibly their setting, and then require the sniffs in our rule set.

### Describe the alternatives that you have considered

N/A

### Additional context

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by antonioeatgoat** [comment]
Personally, I would love to add:

### Functions:
- [SlevomatCodingStandard.Functions.ArrowFunctionDeclaration](https://github.com/slevomat/coding-standard/blob/master/doc/functions.md#slevomatcodingstandardfunctionsarrowfunctiondeclaration-) (If not already covered by other roles. Spacing must be defined).

### Namespaces:
- [SlevomatCodingStandard.Namespaces.AlphabeticallySortedUses](https://github.com/slevomat/coding-standard/blob/master/doc/namespaces.md#slevomatcodingstandardnamespacesalphabeticallysorteduses-).
- [SlevomatCodingStandard.Namespaces.FullyQualifiedExceptions](https://github.com/slevomat/coding-standard/blob/master/doc/namespaces.md#slevomatcodingstandardnamespacesfullyqualifiedexceptions-).
- [SlevomatCodingStandard.Namespaces.MultipleUsesPerLine](https://github.com/slevomat/coding-standard/blob/master/doc/namespaces.md#slevomatcodingstandardnamespacesmultipleusesperline).
- [SlevomatCodingStandard.Namespaces.UseDoesNotStartWithBackslash](https://github.com/slevomat/coding-standard/blob/master/doc/namespaces.md#slevomatcodingstandardnamespacesusedoesnotstartwithbackslash-).
- [SlevomatCodingStandard.Namespaces.UnusedUses](https://github.com/slevomat/coding-standard/blob/master/doc/namespaces.md#slevomatcodingstandardnamespacesunuseduses-).

### PHP:
- [SlevomatCodingStandard.PHP.TypeCast](https://github.com/slevomat/coding-standard/blob/master/doc/php.md#slevomatcodingstandardphptypecast-)
- [SlevomatCodingStandard.PHP.UselessParentheses](https://github.com/slevomat/coding-standard/blob/master/doc/php.md#slevomatcodingstandardphpuselessparentheses-)

### Type hints:
- [SlevomatCodingStandard.TypeHints.UnionTypeHintFormat](https://github.com/slevomat/coding-standard/blob/master/doc/type-hints.md#slevomatcodingstandardtypehintsuniontypehintformat-) with `WhiteSpce` set to `no`.

---

Also. here's a list of things that I would also like to add but I understand they may be too strict or anyway many people could dislike.

### Type hints:
- [SlevomatCodingStandard.TypeHints.ReturnTypeHint](https://github.com/slevomat/coding-standard/blob/master/doc/type-hints.md#slevomatcodingstandardtypehintsreturntypehint-).

--- 

Last thing:

@gmazzap, I think you were referencing to `SlevomatCodingStandard.Namespaces.UnusedUses`, but I cannot see it added within #70 🤔

**Comment by shvlv** [comment]
I would suggest [SlevomatCodingStandard.ControlStructures.DisallowYodaComparison](https://github.com/slevomat/coding-standard/blob/master/doc/control-structures.md#slevomatcodingstandardcontrolstructuresdisallowyodacomparison-). I think we discussed it internally and most part developers agreed that warning will be okay.

**Comment by tfrommen** [comment]
This package is shifting to maintenance mode, so this issue will not be addressed, and therefore be closed.

As part of the work on the new Syde PHP Coding Standards, [`syde/phpcs`](https://github.com/inpsyde/phpcs), the entire Slevomat coding standard got reviewed, and select sniffs have been added to both the `Syde-Core` and the `Syde-Extra` coding standards.
