### ISSUE TITLE
[Feature Request]: Enforce no spaces in array brackets

### ISSUE THREAD

**Issue by antonioeatgoat** [inpsyde/php-coding-standards#91]
### Is your feature request related to a problem?

At the current moment, we don't have any specific rule for spaces around keys in array square brackets.

This means that all the following lines are accepted by our rules:

- `$array['key'];`
- `$array[ 'key' ];`
- `$array[$key];`
- `$array[ $key ];`
- `$array = [ 'test', 'test2']`
- `$array = [ 'test', 'test2' ]`
- `$array = ['test', 'test2']`

### Describe the desired solution

No space should be enforced. Specifically, we could use the rule [SlevomatCodingStandard.Arrays.SingleLineArrayWhitespace](https://github.com/slevomat/coding-standard/blob/master/doc/arrays.md#slevomatcodingstandardarrayssinglelinearraywhitespace-), which allows to configure the number of accepted spaces.

Accepted cases would be:
- `$array['test'];`
- `$array[123];`
- `$array[$test];`
- `$array[TEST];`
- `$array['test' . $test];`
- `$array = ['test', 'test2']`

### Describe the alternatives that you have considered

An alternative solution is using the rule [WordPress.Arrays.ArrayKeySpacingRestrictions](https://github.com/WordPress/WordPress-Coding-Standards/blob/develop/WordPress/Docs/Arrays/ArrayKeySpacingRestrictionsStandard.xml), from [WordPress Coding Standard](https://github.com/WordPress/WordPress-Coding-Standards), it enforces no space around the key, except if the key is a variable, a constant or a concatenated string.

In this case, accepted cases would become:

- `$array['test'];`
- `$array[123];`
- `$array[ $test ];`
- `$array[ TEST ];`
- `$array[ 'test' . $test ];`

### Props
- @widoz suggested it.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Chrico** [comment]
The [SlevomatCodingStandard.Arrays.SingleLineArrayWhitespace](https://github.com/slevomat/coding-standard/blob/master/doc/arrays.md#slevomatcodingstandardarrayssinglelinearraywhitespace-), sounds more consistent the me. 👍🏻

**Comment by tfrommen** [comment]
The Slevomat sniff is not about array access, but array **declaration**.

It will flag things like `$a = [ 'space-before', 'no-space-after']`, but not `$a[ 'space-before-but-not-ater']`.

We may want to use `Squiz.Arrays.ArrayBracketSpacing`, which is part of PHP_CodeSniffer.

**Comment by antonioeatgoat** [comment]
@tfrommen you are correct about Slevomat. I was going to add it and then I realized the problem. I was trying `Squiz.Arrays.ArrayBracketSpacing` locally but I had some problem with it. If it works as expected, it is fine to add it for me.

**Comment by tfrommen** [comment]
Done in #96.
